# Site settings
author: David Bermudez
title: 
header-img: img/home-bg.png
email: juan.bermudez1102@outlook.com
copyright_name: David Bermudez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  david-bermudez1102

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
